---
title: "Second order design"
subtitle: | 
  | ""
author: |
  | Chi-Kuang Yeh
  | University of Waterloo
date: "`r format(Sys.time(), '%d %B, %Y')`"
bibliography: ref.bib
output:
  rmarkdown::html_document:
    theme: readable
    code_folding: hide
    toc: true
    toc_float: yes
    number_sections: true
link-citations: yes
urlcolor: blue
linkcolor: red
---

<!-- latex macros -->
\newcommand{\btheta}{\boldsymbol{\theta}}
\newcommand{\ep}{\varepsilon}
\newcommand{\E}{\mathbb E}

```{r setup, message = F}
library(tibble)
library(dplyr)
library(janitor) # to add the sum/total
library(knitr)
library(kableExtra)

partial_deri_second <- function(xi, wi, beta){
  fxi <- c(1, xi[1], xi[2], xi[1]^2, xi[2]^2, xi[1]*xi[2]) 
  wi * fxi %o% fxi
}
```

```{r}
n <- 21
design_app <- matrix(c(0,            0,      0.35984,
                       0,         2.25,     0.045446,
                       0,          2.5,      0.11032,
                       0,            5,     0.017909,
                       2.25,            0,     0.045446,
                       2.25,         2.25,     0.011375,
                       2.25,         2.5,     0.019334,
                       2.25,            5,    0.0087029, 
                       2.5,            0,      0.11032,
                       2.5,         2.25,     0.019333,
                       2.5,          2.5,      0.10429,
                       2.5,            5,     0.039803,
                       5,            0,     0.017909,
                       5,         2.25,    0.0087034,
                       5 ,         2.5,     0.039802,
                       5 ,           5,     0.041467), byrow = F, nrow = 3)
design_ex <- matrix(c(0,            0,            8,
                       0,       2.6465,            1,
                       0,        2.647,            1,
                       0,            5,            3,
                       2.4818,       2.0625,            1,
                       2.4827,       2.0645,            1,
                       2.4831,       2.0606,            1,
                       2.6938,            5,            1,
                       5,            0,            3,
                       5,       3.4283,            1,
                       5,            5,            1), byrow = F, nrow = 3)
design_app_tbl <- tibble(x1 = design_app[1,], x2 = design_app[2, ], weight = design_app[3,])
design_ex_tbl <- tibble(x1 = design_ex[1,], x2 = design_ex[2, ], weight = design_ex[3,]/n)
design_weight <- design_ex[,3]/n
calc_loss_2d <- function(design, beta, q, f){
  point <- cbind(design$x1, design$x2)
  weight <- design$weight
  n_x <- nrow(design) 
  FIM <- matrix(0, nrow = q, ncol = q)
  for(i in 1:n_x){
    FIM <- FIM + f(xi = point[i, ], weight[i], beta)
  }
  # 
  list(Dopt = -log(det(FIM)^(1/q)),
       Aopt = sum(diag(solve(FIM)))
  )
}
make_tbl_loss_2d_A <- function(design_app_tbl, design_ex_tbl, f, beta){
  tibble(tyep = c("approx", "exact"),
        loss = c(calc_loss_2d(design_app_tbl, rep(1,6), q = length(beta),
                                f = f)$Aopt, 
                calc_loss_2d(design_ex_tbl, beta, q = length(beta),
                                f = f)$Aopt)) %>% 
  mutate(across(where(is.numeric), ~ num(., digits = 5)))
}
make_tbl_loss_2d_A(design_app_tbl, design_ex_tbl, f = partial_deri_second, rep(1,6))
```

